---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
        - i3
        - rofi
        - xinit
        - x11-xserver-utils
        - xclip
        - fonts-noto-color-emoji
        - pulseaudio
        - pavucontrol
        - feh
        - w3m-img # used for ranger image preview
        - dunst
        - xdotool
        - zathura
        - brightnessctl
        - flameshot
        - picom
        - playerctl
        - papirus-icon-theme
        - udiskie
        - ibus # nicer input management (applet, emojis)
        - alacritty
        - libx11-dev # used in building fancy lock
        - python3-pil # used in media notification
        - redshift # screen lumen for night
    become: yes

  - name: Create config folders
    file:
      path: "{{ item }}"
      state: directory
      recurse: yes
    with_items:
      - ~/.local/share/applications
      - ~/.config/alacritty
      - ~/.config/dunst
      - ~/.config/picom
      - ~/.config/rofi
      - ~/.config/zathura
      - ~/.config/fontconfig
      - ~/.i3

  - name: Create soft links
    file:
      src: "~/Documents/config/{{ item.path }}"
      dest: "~/{{ item.dest }}"
      state: link
      force: yes
    with_items:
      - { path: 'xdg/mimeapps.list', dest: '.local/share/applications/mimeapps.list' }
      - { path: 'X/resources', dest: '.Xresources' }
      - { path: 'X/.xinitrc', dest: '.xinitrc' }
      - { path: 'alacritty/alacritty.yml', dest: '.config/alacritty/alacritty.yml' }
      - { path: 'alacritty/alacritty_sonokai.yml', dest: '.config/alacritty/alacritty_sonokai.yml' }
      - { path: 'picom/picom.conf', dest: '.config/picom/picom.conf' }
      - { path: 'i3/i3.conf', dest: '.i3/config' }
      - { path: 'i3/status.conf', dest: '.i3/i3status.conf' }
      - { path: 'i3/py3status', dest: '.i3/py3status' }
      - { path: 'dunst/dunstrc', dest: '.config/dunst/dunstrc' }
      - { path: 'rofi/config.rasi', dest: '.config/rofi/config.rasi' }
      - { path: 'bash/.bash_profile', dest: '.bash_profile' }
      - { path: 'zathura/zathurarc', dest: '.config/zathura/zathurarc' }
      - { path: 'font/fonts.conf', dest: '.config/fontconfig/fonts.conf' }

  - name: Install nerd font
    shell: |
      mkdir -p /tmp/nerdfont/patched-fonts/UbuntuMono
      cd /tmp/nerdfont
      curl -OL https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/install.sh
      curl -OL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/UbuntuMono.tar.xz
      tar -xf UbuntuMono.tar.xz -C patched-fonts/UbuntuMono
      chmod +x install.sh
      ./install.sh UbuntuMono
      rm -rf /tmp/nerdfont
    args:
      creates: ~/.local/share/fonts/NerdFonts

  - name: Get i3lock fancy rapid
    git:
        repo: 'https://github.com/yvbbrjdr/i3lock-fancy-rapid'
        dest: ./compile/i3lock

  - name: Build i3lock fancy rapid
    make:
        chdir: ./compile/i3lock

  - name: Set update alternatives
    community.general.alternatives:
      name: x-terminal-emulator
      path: /usr/bin/alacritty
    become: yes
