---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
        - unzip
        - neovim
        - git
        - curl
        - ranger
        - ack
        - bash-completion
        - python3-pip
        - nodejs
        - npm
    become: yes

  - name: Create config folders
    file:
      path: "{{ item }}"
      state: directory
      recurse: yes
    with_items:
      - ~/Documents
      - ~/.config/ranger
      - ~/.config/nvim/autoload

  - name: Clone config files
    git:
      repo: 'https://github.com/david-westreicher/config'
      dest: ~/Documents/config

  - name: Create soft links
    file:
      src: "~/Documents/config/{{ item.path }}"
      dest: "~/{{ item.dest }}"
      state: link
      force: yes
    with_items:
      - { path: 'ls/dircolors.nord', dest: '.dircolors' }
      - { path: 'ranger/rc.conf', dest: '.config/ranger/rc.conf' }
      - { path: 'nvim/init.vim', dest: '.config/nvim/init.vim' }
      - { path: 'nvim/coc-settings.json', dest: '.config/nvim/coc-settings.json' }

  - name: Add bashrc config
    lineinfile:
      dest: ~/.bashrc
      line: '. ~/Documents/config/bash/bashrc'
      insertafter: EOF

  - name: Install python
    pip:
      name: [black]
      executable: pip3
    become: yes

  - name: Install vim-plug for neovim
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: ~/.config/nvim/autoload/plug.vim

  - name: Install nvim plugins
    command: "nvim +PlugInstall +qall"

  - name: Build docker images
    docker_image:
      name: "{{ item.dest }}"
      build:
        path: "~/Documents/config/scripts/{{ item.path }}"
      source: build
    with_items:
        - { path: 'latex/Dockerfile', dest: 'latex_tools'}

  - name: Install linked software
    copy:
      src: "~/Documents/config/scripts/{{ item.path }}"
      dest: "/usr/local/bin/{{ item.path }}"
      force: yes
      mode: u=rwx,g=rx,o=rx
    with_items:
      - { path: 'latexmk' }
    become: yes
