---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
        - unzip
        - avahi-daemon
        - git
        - git-lfs
        - curl
        - ranger
        - ack
        - bash-completion
        - python3-pip
        - pipx
        - nodejs
        - npm
        - cookiecutter
        - fzf
        - direnv
        - snapd # for neovim 0.9.2
        - khal # nicer calendar
    become: yes

  - name: Create config folders
    file:
      path: "{{ item }}"
      state: directory
      recurse: yes
    with_items:
      - ~/Documents
      - ~/.config/ranger

  - name: Install diff-so-fancy for nice git diff messages
    community.general.npm:
      name: diff-so-fancy
      global: true
      state: present
    become: yes

  - name: Create soft links
    file:
      src: "~/Documents/config/{{ item.path }}"
      dest: "~/{{ item.dest }}"
      state: link
      force: yes
    with_items:
      - { path: 'ls/dircolors.nord', dest: '.dircolors' }
      - { path: 'git/config', dest: '.gitconfig' }
      - { path: 'ranger/rc.conf', dest: '.config/ranger/rc.conf' }
      - { path: 'nvim', dest: '.config/nvim' }

  - name: Add bashrc config
    lineinfile:
      dest: ~/.bashrc
      line: '. ~/Documents/config/bash/bashrc'
      insertafter: EOF

  - name: Install global python dependencies
    community.general.pipx:
      name: "{{ item }}"
    with_items:
      - black
      - mypy

  - name: Update snap to latest
    community.general.snap:
      name: core
    become: yes

  - name: Install nvim via snap
    community.general.snap:
      name: nvim
      classic: true
    become: yes

  - name: Install global node dependencies
    community.general.npm:
      name: neovim
      global: true
    become: yes

  - name: Install pyenv
    command: curl https://pyenv.run | bash
    args:
      creates: ~/.pyenv/bin/pyenv

  - name: Update LazyVim
    command: /snap/bin/nvim +"lua require('lazy').restore({wait=true})" +qa


      # - name: Build docker images
      #   docker_image:
      #     name: "{{ item.dest }}"
      #     build:
      #       path: "~/Documents/config/scripts/{{ item.path }}"
      #     source: build
      #   with_items:
      #       - { path: 'latex/Dockerfile', dest: 'latex_tools'}

      # - name: Install linked software
      #   copy:
      #     src: "~/Documents/config/scripts/{{ item.path }}"
      #     dest: "/usr/local/bin/{{ item.path }}"
      #     force: yes
      #     mode: u=rwx,g=rx,o=rx
      #   with_items:
      #     - { path: 'latexmk' }
      #   become: yes
