---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
        - i3
        - i3lock-fancy
        - rofi
        - xinit
        - x11-xserver-utils
        - feh
        - lxterminal
        - python3-pip
        - fonts-font-awesome
        - dunst
        - nodejs
        - npm
        - xdotool
        - zathura
        - neovim
    become: yes

  - name: Create nvim config folder
    file:
      path: ~/.config/nvim/autoload/
      state: directory

  - name: Install vim-plug for neovim
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: ~/.config/nvim/autoload/plug.vim

  - name: Install i3 dependencies
    pip:
      name: [py3status, i3ipc, mypy, "python-language-server[all]", flake8, black, isort]
      executable: pip3
    become: yes

  - name: Create config folders
    file:
      path: "{{ item }}"
      state: directory
      recurse: yes
    with_items:
      - ~/.local/share/fonts
      - ~/.local/share/applications
      - ~/.config/lxterminal
      - ~/.config/dunst
      - ~/.i3

  - name: Create soft links
    file:
      src: "~/Documents/config/{{ item.path }}"
      dest: "~/{{ item.dest }}"
      state: link
      force: yes
    with_items:
      - { path: 'xdg/mimeapps.list', dest: '.local/share/applications/mimeapps.list' }
      - { path: 'X/resources', dest: '.Xresources' }
      - { path: 'lxterminal/lxterminal.conf', dest: '.config/lxterminal/lxterminal.conf' }
      - { path: 'i3/i3.conf', dest: '.i3/config' }
      - { path: 'i3/status.conf', dest: '.i3/i3status.conf' }
      - { path: 'i3/py3status', dest: '.i3/py3status' }
      - { path: 'nvim/init.vim', dest: '.config/nvim/init.vim' }
      - { path: 'nvim/coc-settings.json', dest: '.config/nvim/coc-settings.json' }
      - { path: 'dunst/dunstrc', dest: '.config/dunst/dunstrc' }
      - { path: 'bash/.bash_profile', dest: '.bash_profile' }

  - name: Install linked software
    copy:
      src: "~/Documents/config/scripts/{{ item.path }}"
      dest: "/usr/local/bin/{{ item.path }}"
      force: yes
      mode: u=rwx,g=rx,o=rx
    with_items:
      - { path: 'latexmk' }
    become: yes

  - name: Install twitter emoji
    unarchive:
        src: "https://github.com/eosrei/twemoji-color-font/releases/download/v13.0.1/TwitterColorEmoji-SVGinOT-Linux-13.0.1.tar.gz"
        dest: "~/.local/share/fonts/"
        remote_src: yes

  - name: Install noto emoji
    unarchive:
        src: "https://noto-website-2.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip"
        dest: "~/.local/share/fonts/"
        remote_src: yes

  - name: Install fonts
    command: "fc-cache -f -v"

  - name: Install nvim plugins
    command: "nvim +PlugInstall +qall"
