set nocompatible              " be iMproved, required
filetype off                  " required

" ############################
" MY SETTINGS
" ###########################

" color
set background=light

" make backspace work
set bs=2 

" make copy&paste work
set pastetoggle=<F9>
set clipboard=unnamedplus
vmap p "_dP

" mouse
set mouse=a

" unbind arrow keys :D
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" down is next wrap line not just line
nnoremap j gj
nnoremap k gk

" quicksave/quickquit
noremap <C-S> :w<CR>
inoremap <c-s> <Esc>:w<CR>
noremap <C-Q> :q<CR>
inoremap <c-q> <Esc>:q<CR>

" better indentation
vnoremap < <gv
vnoremap > >gv


" ide settings
set number
set tw=0
highlight LineNr ctermfg=grey
highlight Search ctermfg=black

" use spaces 
set autoindent
" set noexpandtab
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smartindent
set shiftround
set copyindent
set preserveindent

" File extensions
au BufReadPost *.mc set syntax=c

" ############################
" VUNDLE START
" ###########################
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

" ############################
" MY PLUGINGS
" ###########################

" AIRLINE
Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
set laststatus=2
if !exists('g:airline_symbols')
	let g:airline_symbols = {}
endif
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'
let g:airline#extensions#tabline#enabled = 1
let g:airline_solarized_bg='dark'
let g:airline_theme='solarized'

"GIT
Plugin 'airblade/vim-gitgutter'

"CTRLP
Plugin 'kien/ctrlp.vim'
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git\|data\'

"Multiple Cursors
Plugin 'terryma/vim-multiple-cursors'

" signatures
Plugin 'kshenoy/vim-signature'

" autopep8
Plugin 'tell-k/vim-autopep8'
let g:autopep8_ignore='E501'

" ide
Plugin 'scrooloose/nerdtree'

" Dockerfile
Plugin 'ekalinin/Dockerfile.vim'

" Ansible
Plugin 'pearofducks/ansible-vim'

" Search
Plugin 'ddrscott/vim-side-search'

" Typescript
Plugin 'leafgarland/typescript-vim'

" Vue
Plugin 'posva/vim-vue'

" Linter
" Plugin 'w0rp/ale'
" highlight ALEError ctermbg=blue

" Jedi
" Plugin 'davidhalter/jedi-vim'
" let g:jedi#use_tabs_not_buffers = 1

" ############################
" VUNDLE END
" ###########################
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"

" syntax
syntax enable
filetype plugin on
