# This configs were added by https://github.com/david-westreicher/config/installconfigs.sh
# use 256 colors, disable ctrl+s
export TERM=xterm-256color
export EDITOR=nvim
export VISUAL=nvim

# Increase bash history
export HISTFILESIZE=
export HISTSIZE=1000000
export HISTFILE='/home/david/.bash_history_eternal'
# export FZF_DEFAULT_OPTS='--history-size=100000'
# save history on every command
shopt -s histappend
PROMPT_COMMAND="history -a;$PROMPT_COMMAND"

bind -r '\C-s'
stty -ixon -ixoff
PS1='${debian_chroot:+($debian_chroot)}\
\[\033[01;31m\]😃 \[\033[1m\]\u\[\033[00m\] \
\[\033[01;32m\]💻 \[\033[1m\]\h\[\033[00m\] \
\[\033[01;34m\]📁 \[\033[1;4m\]\w\[\033[00m\] \
\n➤ '

alias python='python3'
torrents() { python ~/Documents/config/scripts/torrent.py "$@"; }
alias multiscreen='python2 ~/Documents/config/scripts/multiscreen.py'
alias forall='python3 ~/Documents/config/scripts/forall.py'
alias cal='khal calendar'
alias haskell='ghci'
alias wetter='curl wttr.in/Innsbruck'
alias search='ack -i'
alias competitive='cookiecutter ~/Documents/config/cookiecutter/competitive/'
alias music='cmus'
alias vim='nvim'
alias vps='ssh david@vps -i ~/.ssh/vps'
alias clipboard='xclip -sel clip'
alias largest='du -a $1 | sort -n -r | head -n 10'
alias showimg='feh --draw-filename --scale-down --recursive --quiet --thumb-height 120 --thumb-width 120'
alias pytorch='nvidia-docker run -it --rm --net="host" -v $(pwd):/workspace --entrypoint "python" pytorch/pytorch:latest'
alias jupyter-lab='nvidia-docker run -it --rm --net="host" -v $(pwd):/workspace --entrypoint "jupyter-lab" pytorch/pytorch:latest --allow-root --ip 0.0.0.0'
alias tree='tree -I "node_modules|.env|__pycache__"'
alias ..='cd ..'

if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
	alias ll='ls -l -a -h -N --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi

# color man pages
export MANPAGER="less -R --use-color -Dd+r -Du+b"
export MANROFFOPT="-P -c"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$PYENV_ROOT/shims:$PATH"
eval "$(pyenv init -)"

#go
export PATH="/home/david/go/bin:$PATH"

# pipx
export PATH="/home/david/.local/bin:$PATH"

# fuzzy file search
source /usr/share/doc/fzf/examples/key-bindings.bash
source /usr/share/bash-completion/completions/fzf
# source /usr/share/doc/fzf/examples/completion.bash
# export DOCKER_HOST="unix:///mnt/wsl/shared-docker/docker.sock"

# make ctrl-w (word delete) in bash nicer
stty werase undef
bind '\C-w:unix-filename-rubout'

# load direnv
eval "$(direnv hook bash)"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/david/.mujoco/mujoco210/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia

# flutter
# export PATH="$PATH:/home/david/snap/flutter/common/flutter/bin"
export PATH="$PATH:/snap/bin"
export ANDROID_HOME=$HOME/android/sdk
export PATH=$ANDROID_HOME/cmdline-tools/tools/bin/:$PATH
export PATH=$ANDROID_HOME/emulator/:$PATH
export PATH=$ANDROID_HOME/platform-tools/:$PATH
